### ISSUE TITLE
最低限の機能を考える

### ISSUE THREAD

**Issue by sosukemikami3** [sgmikami03/portfolio_app#1]

**Comment by sosukemikami3** [comment]
### 認証系
- [x] ログインログアウト (supabase)
- [ ] googleログイン

### データ管理
- [x] supabaseを使いたい
- [x] 画像 upload機能
- [x] works CRUD
- [x] user CRUD

**Comment by sosukemikami3** [comment]
### todo
- [x] プロジェクト作成
- [x] DB接続
- [x] ChakuraUI 導入
- [ ] next-auth導入 (やらない)

**Comment by sosukemikami3** [comment]
### 画面 (アプリとして成り立たせるならこのライン)
#### 認証系
- [x] 認証系など

#### works系
- [x] "/" home ほぼworks一覧 一旦全件取得
- [x] "/work/[id]"
- [x] "/work/[id]/edit/"
- [x] "work/new/"
- [x] "work/list/[page]/

#### ユーザ系
- [x] "/profile/[user_id]/" ユーザー情報
- [x] "/profile/[user_id]/works" ワークス一覧
